---
title: "Music Album Analysis"
author: 

output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: minty
runtime: shiny
---

```{r setup, include=FALSE}
library(shiny)
library(shinydashboard)
library(flexdashboard)
library(tidyverse)
library(sf)
library(ggplot2)
library(tidygraph)
```

```{r}
data <- read.csv(file="album.csv", sep=",", header = TRUE)
```


```{r include=FALSE}
#Check for missing values 
sum(is.na(data))
```

```{r include=FALSE}
#Divide the third column into two separate columns named 'year' and 'title'
data <- data %>%
  separate(album, into = c("year", "title"), sep = " ", extra = "merge") 

#Remove the brackets
years <- gsub("[()]", "", data$year ) 
data$year <- years 
```


```{r include=FALSE}
# Create a new dataframe with the name "artists" which contains:
#(a) the artists' names
#(b) both their first two genres

artists <- data[,c('artist','genre')]

#Take the first two elements of the 'genre' column
#Create two new columns named "primary_genre", "secondary_genre"
artists <- artists %>%
  separate(genre, into = c("primary_genre", "genre"), sep=",") %>%
  separate(genre, into = "secondary_genre", sep=",")

#In artists with only one genre the same is used in both columns
for(row in 1:nrow(artists)) {
  if (is.na(artists$secondary_genre[row])) {
    artists$secondary_genre[row] = artists$primary_genre[row] 
  }
}

```

```{r include=FALSE}
#Create the dataframe "albums" 
albums <- data %>% 
  #Eliminate the genres that are not unique
  mutate(genre = map(str_split(genre, ','), ~ paste(unique(.x), collapse = ','))) %>% 
  #Divide the genres into columns
  separate(col = 1, into = paste0('genre', seq(max(str_count(data$genre, ',')) + 1L)), sep = ',')
```

Page 1
=====================================  
    

Column {data-width=300}
-------------------------------------

### Select year range 

```{r}
sliderInput("slider", label = h3("Slider Range"), min = 1938, 
  max = 2020, value = c(1938, 2020))
```   

Column {data-width=700}
-------------------------------------

### The evolution of music

```{r}
renderPlot({
#Distribution of albums per year
data_by_year <- data %>% 
  group_by(year) %>%
  summarise(number_of_albums = n())

data_by_year$year <- as.numeric(data_by_year$year)

ggplot(data = filter(data_by_year, year > input$slider[1] & year < input$slider[2]),aes(year, number_of_albums)) +
  geom_bar(stat='identity', color="#2596BE", fill = "lightblue") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=2)) +
  theme(axis.text = element_text(size = 8))
})  
```


   
Page 2 
=====================================     
Column {data-width=300}
-------------------------------------
   
### Check the evolution of each genre 

```{r}
radioButtons("radio", label = h3("Choose a genre:"),
             c("All" = "all", "Blues" = "bl", "International" = "int", "Jazz" = "j", 
               "Pop-Rock" = "pr", "R&B" = "rb"))
```     


Column {data-width=700}
-------------------------------------

### Τop 5 Genre of All Time

```{r}
renderPlot({
  #Distribution of the top 5 genre over time
  top_five <- albums %>%
    select(title, genre1) %>%
    group_by(genre1) %>%
    summarise(count = n(), .groups ='drop') %>%
    arrange(desc(count)) %>%
    slice(1:5)
  
  albums_of_top5 <- albums %>%
    select(year, title, genre1) %>%
    filter(genre1 == top_five$genre1) %>%
    group_by(year, genre1) %>%
    summarise(number_of_albums = n(), .groups = 'drop')
      
  choice <- switch(input$radio,
              all = "All",
              bl = "Blues",
              int = "International",
              j = "Jazz",
              pr = "Pop-Rock",
              rb = "R&B",
              "All")

  if (choice == "All") { 
    ggplot(albums_of_top5, aes(year, number_of_albums, fill=genre1)) +
      geom_bar(stat='identity') +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=2)) +
      theme(axis.text = element_text(size = 6)) +
      guides(fill=guide_legend(title="Top 5 Genres"))
  } else {   
    ggplot(data = filter(albums_of_top5, genre1 == choice), aes(year, number_of_albums, fill=genre1)) +
      geom_bar(stat='identity') +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=2)) +
      theme(axis.text = element_text(size = 6)) +
      guides(fill=guide_legend(title="One of the top 5 genres"))
  }
})
```


Page 3 
===================================== 

Column {data-width=300}
-------------------------------------
   
###  Which albums contain countries in their titles ?
```{r include=FALSE}
world <- st_read(system.file("shapes/world.gpkg", package="spData"))
```

```{r}
selectInput("country", label = h3("Select a country:"), c("All", world$name_long), 
            selected = NULL, multiple = FALSE, selectize = F)
```   
   
Column {data-width=700}
-------------------------------------

### Let's find out !

```{r include=FALSE}

country_in_title <- data.frame(country = world$name_long, pos = 0) #geometry = world$geom

for (i in 1:nrow(world)) {
  country_in_title$pos[i] <- list(which(grepl(world$name_long[i], albums$title) == TRUE))
}

country_in_title$pos[country_in_title$pos == "integer(0)"] <- 0

country_in_title$pos <- gsub("c", "", country_in_title$pos)
country_in_title$pos <- gsub("[()]", "", country_in_title$pos)

country_in_title <- country_in_title %>%
  separate_rows(pos, sep = ", ") %>%
  distinct()

albums_with_country <- albums %>%
  select(title) %>%
  mutate(country = 0) 

for (r in 1:nrow(country_in_title)) {
  if (country_in_title$pos[r] != "0") {
    num <- as.numeric(country_in_title$pos[r])
    albums_with_country$country[num] <- country_in_title$country[r] 
  } 
}

albums_with_country <- albums_with_country %>%
  filter(albums_with_country$country != 0) %>%
  group_by(country) %>%
  summarise(number_of_albums = n(), .groups = 'drop')

world <- world %>%
  mutate(number_of_albums = 0)

for (r in 1:nrow(albums_with_country)) {
  c <- albums_with_country$country[r]
  world$number_of_albums[world$name_long == c] <- albums_with_country$number_of_albums[r] 
}
```  

```{r}
renderPlot({
  c <- toString(input$country)
  
  if (c == "All") { 
    ggplot(data = world) +
      geom_sf(color = "black", fill = "lightblue") +
      geom_sf_label(data = world, aes(label = number_of_albums), size = 2) +
      theme_void()
  } else {
      ggplot(data = filter(world, name_long == c)) + 
      geom_sf(color = "black", fill = "#E78AC3") +
      geom_sf_label(data = filter(world, name_long == c), 
                    aes(label = number_of_albums), size = 8) +
      theme_void()
  }
})
```



    
